Multiple Linear regression using the Sklearn


In [19]:
import numpy as np 
from sklearn.datasets import load_diabetes


In [20]:
X,y = load_diabetes(return_X_y=True)

In [21]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [5]:
X.shape


(442, 10)

In [6]:
y


array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [7]:
y.shape


(442,)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2,random_state = 42)

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
reg = LinearRegression()

In [12]:
reg.fit(X_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [13]:
y_pred = reg.predict(X_test)

In [14]:
from sklearn.metrics import r2_score

In [15]:
r2_score(y_test,y_pred)

0.4526027629719195

In [16]:
reg.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [18]:
reg.intercept_

np.float64(151.34560453985995)

Multiple Linear Regression using the Own class

In [40]:
class MeraLR:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train= np.insert(X_train,0,1,axis=1)

        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.coef_ = betas[1:]
        self.intercept_ = betas[0]

    def predict(self,X_test):
        print(X_test)

        return np.dot(X_test,self.coef_) + self.intercept_
        

In [41]:
import numpy as np 
from sklearn.datasets import load_diabetes


In [42]:
X,y = load_diabetes(return_X_y=True)

In [43]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2,random_state = 42)

In [44]:
mlr = MeraLR()


In [45]:
mlr.fit(X_train,y_train)

In [46]:
y_pred = mlr.predict(X_test)

[[ 0.04534098 -0.04464164 -0.00620595 -0.01599898  0.1250187   0.1251981
   0.019187    0.03430886  0.03243232 -0.0052198 ]
 [ 0.09256398 -0.04464164  0.03690653  0.02187239 -0.02496016 -0.01665815
   0.00077881 -0.03949338 -0.02251653 -0.02178823]
 [ 0.06350368  0.05068012 -0.00405033 -0.01255612  0.10300346  0.04878988
   0.05600338 -0.00259226  0.08449153 -0.01764613]
 [ 0.09619652 -0.04464164  0.0519959   0.07926471  0.05484511  0.03657709
  -0.07653559  0.14132211  0.09864806  0.06105391]
 [ 0.01264814  0.05068012 -0.02021751 -0.00222757  0.03833367  0.05317395
  -0.00658447  0.03430886 -0.00514219 -0.00936191]
 [ 0.0090156  -0.04464164 -0.02452876 -0.02632753  0.0988756   0.0941964
   0.07072993 -0.00259226 -0.02139531  0.00720652]
 [-0.00914709  0.05068012  0.17055523  0.01498668  0.03007796  0.03375875
  -0.02131102  0.03430886  0.03365381  0.03205916]
 [-0.02367725  0.05068012  0.04552903  0.02187239  0.10988322  0.08887288
   0.00077881  0.03430886  0.0741909   0.06105391]
 [

In [47]:
r2_score(y_test,y_pred)

0.45260276297191915

In [48]:
mlr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [49]:
mlr.intercept_

np.float64(151.34560453986)